spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xc_content?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    password: A10ne,tillde@th.

xxl:
  job:
    admin: 
      addresses: http://192.168.101.128:18088/xxl-job-admin/
    executor:
      appname: course-publish-job
      address:
      ip:
      port: 10999
      logpath: /data/applogs/xxl-job-jobhandler
      logretentiondays: 30
    accessToken: default_token