server:
  port: 53010 # 网关端口
spring:
  cloud:
    gateway:
      routes: 
        - id: content-api # 路由id，自定义，只要唯一即可
          uri: lb://content-api # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/content/** # 这个是按照路径匹配，只要以/content/开头就符合要求
        - id: system-api
          uri: lb://system-api
          predicates:
            - Path=/system/**
        - id: media-api
          uri: lb://media-api
          predicates:
            - Path=/media/**
        - id: search
          uri: lb://search
          predicates:
            - Path=/search/**
        - id: checkcode
          uri: lb://checkcode
          predicates:
            - Path=/checkcode/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: learning-api
          uri: lb://learning-api
          predicates:
            - Path=/learning/**
        - id: orders-api
          uri: lb://orders-api
          predicates:
            - Path=/orders/**