spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xc_learning?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: A10ne,tillde@th.